baseurl:        "http://support.growthbeat.com/"
title:          "Growthbeat | docs"
contentdir:     "content"
publishdir:     "public"
layoutdir:      "layouts"
staticdir:      "static"
uglyUrls:       false
metaDataFormat: "yaml"

Params:
  # Date Format
  DateForm:      "Mon, Jan 2, 2006"
